use colored::Colorize;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;

// Serialize means "convert to toml text"
// Deserialize means "read from toml text"
// These are automatically generated by serde
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Config {
    pub output_dir: String,
    pub format: String,
    pub max_parallel_downloads: usize,
}

// This is what the config looks like if no file exists yet
impl Default for Config {
    fn default() -> Self {
        Config {
            output_dir: "./music".to_string(),
            format: "mp3".to_string(),
            max_parallel_downloads: 3,
        }
    }
}

// Returns the path to ~/.config/music-dl/config.toml
pub fn config_path() -> PathBuf {
    let base = dirs::config_dir()
        .expect("Could not find config directory");
    base.join("music-dl").join("config.toml")
}

pub fn load() -> Config {
    let path = config_path();

    if path.exists() {
        // Read the file to a string
        let contents = fs::read_to_string(&path)
            .expect("Could not read config file");

        // Parse the toml string into our Config struct
        match toml::from_str(&contents) {
            Ok(config) => config,
            Err(e) => {
                eprintln!("{} {}", "Warning: invalid config file:".yellow(), e);
                eprintln!("Using defaults instead.");
                Config::default()
            }
        }
    } else {
        // First run — create a default config file
        let config = Config::default();
        save(&config);
        println!(
            "{} {}",
            "Created default config at:".cyan(),
            path.display().to_string().yellow()
        );
        config
    }
}

pub fn save(config: &Config) {
    let path = config_path();

    // Create the directory if needed (~/.config/music-dl/)
    fs::create_dir_all(path.parent().unwrap())
        .expect("Could not create config directory");

    // Convert our Config struct to a toml string
    let contents = toml::to_string_pretty(config)
        .expect("Could not serialize config");

    fs::write(&path, contents)
        .expect("Could not write config file");
}