name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build & Test
    runs-on: windows-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache Rust (Pour accélérer la CI)
        uses: Swatinem/rust-cache@v2

      - name: Vérification du formatage
        run: cargo fmt --all -- --check

      - name: Linter (Clippy)
        # On ne bloque pas la CI sur les warnings pour l'instant, 
        # mais tu pourras rajouter "-- -D warnings" quand ton code sera nickel
        run: cargo clippy --all-targets --all-features

      - name: Lancement des tests (EpiKodi + Plugins)
        # --workspace permet de tester EpiKodi ET tes dossiers de plugins s'ils sont dans un workspace
        run: cargo test --workspace --verbose